# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/askey/wade/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),wade)

$(call add-radio-file-sha1-checked,radio/bootloader.img,a32916577f740646c3df4e4cd3f6a786b83c7352)

endif
