# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/askey/wade/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),wade)

$(call add-radio-file-sha1-checked,radio/bootloader.img,be0a4a559d3be5fb08b536c2678cbf8a73e08fc2)

endif
