# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/askey/wade/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),wade)

$(call add-radio-file-sha1-checked,radio/bootloader.img,3bd7dbb76e59641d5516e06e81ea63dff4050cb9)

endif
